### ISSUE TITLE
copy/paste shortcuts

### ISSUE THREAD

**Issue by jb-tlm** [jb-tlm/color-charter#1]
Fix needed for hex/hsl/rbg input fields of the "set color" button to allow for copy & paste shortcuts - both keyboard & right click.

**Comment by oscisn93** [comment]
Hey, so I just had a look at the recent comments and I have to agree that this is not necessarily an impossible solution, however I will agree that this may require refactoring to an extent that the original code is significantly altered and may have large parts of inspiration from other tools such as those mentioned.
I was thinking that I could add a shortcut, preferably one that is familiar to users, as well as a small dialogue that pops up when users hover over the color picker that tells users the shortcut just in case. Additionally I wanted to add a radio button, but Im not sure how much i can customize the color picker so I will experiment with that. 
Does that sound like a reasonable solution?
