### ISSUE TITLE
Remove unused menu button that is in small screen sizes

### ISSUE THREAD

**Issue by annamkbenson** [jb-tlm/color-charter#35]
Remove (now unused) menu button from the top right of the app on smaller screens (basically under 1020 width). This feature was disabled in a previous fix but it looks like the button/icon was not fully removed. 

![Screenshot 2023-07-28 2 34 11 PM](https://github.com/jb-tlm/color-charter/assets/108377086/e0bb9a87-dd1e-44e9-b4f9-33877cae1368)

**Comment by marcioreisjr** [comment]
Resolved as part of Pull request #38, integrated on bug #36.
